### ISSUE TITLE
Crashing due to motion blur

### ISSUE THREAD

**Issue by David10238** [MechanicalMemes/uWu-Bot#1]
If you shake the phone or the mineral quickly while using "Gold Detect", it will freeze the video and eventually crash the app Robot Controller app. I tried it with "MineralRowTestOpMode". I was able to momentarily freeze it a couple times, but I couldn't make the app crash. I am using a Samsung Galaxy S5 Active RC and a ZTE Speed DS.

**Comment by victoryforphil** [comment]
Thanks for the feedback! I'll definitely look into this case as it's awesome to catch this before the lib is even live. Do keep in mind however this is far from official so expect stuff like this. This is literally my working directory so lots of stuff is incomplete. I'm currently porting the whole system over.

However if this is a bug in the CV logic it will be great to catch and it's amazing to have people already testing my code as I develop! Keep it up.

**Comment by victoryforphil** [comment]
Alright, so I haven't been able to replicate this. I'm figuring this was hopefully fixed during my code refactor. However, if this is still present, please re-report it in the DogeCV repo. Thank you :)
